# Autogenerated by SCAM 0.7.0


scam-all: scam-all-subdirs scam-all-local
prefix=/usr/


#
# Now user added rules (maybe modified by scams)
#

NAME=onion
VERSION=0.0.1
FULLNAME=onion-0.0.1
SCAM_CHECK_DEPENDS=yes
CXX=g++
CC=g++
CXXFLAGS+=-I/usr/share/qt4/include/QtCore
CXXFLAGS+=-I/usr/share/qt4/include/QtGui
CXXFLAGS+=-I/usr/share/qt4/include
CXXFLAGS+=-DQT_THREAD_SUPPORT
LDFLAGS+=-L/usr//lib
LDFLAGS+=-lQtNetwork
MOC=/usr/share/qt4/bin/moc
UIC=/usr/share/qt4/bin/uic
CXXFLAGS+=-O2 -Werror -Wall
TOTAL_COMPILE=0

.depends: 
	touch .depends

include .depends

# Additional tagets by scam:
DISTBASE=./onion-0.0.1/


dist: 
	rm -rf $(DISTBASE) || true
	mkdir -p $(DISTBASE)
	cp configure $(DISTBASE)
	cp Makefile.scam $(DISTBASE)
	cp README $(DISTBASE)
	cp dirlist.html $(DISTBASE)
	cp error.html $(DISTBASE)
	cp example.config $(DISTBASE)
	cp test.html $(DISTBASE)
	(cd src && make dist)
	tar cvfz onion-0.0.1.tar.gz onion-0.0.1
	rm -rf onion-0.0.1
	@echo Created onion-0.0.1.tar.gz


dist2: 
	rm -rf $(DISTBASE) || true
	mkdir -p $(DISTBASE)
	cp configure $(DISTBASE)
	cp Makefile.scam $(DISTBASE)
	cp README $(DISTBASE)
	cp dirlist.html $(DISTBASE)
	cp error.html $(DISTBASE)
	cp example.config $(DISTBASE)
	cp test.html $(DISTBASE)
	(cd src && make dist)
	tar cvfj onion-0.0.1.tar.bz2 onion-0.0.1
	rm -rf onion-0.0.1
	@echo Created onion-0.0.1.tar.bz2


scam-all-local: 

scam-all-subdirs: 
	(cd src && ( $(MAKE) .depends || true ) && $(MAKE) )


distclean: clean
	@rm -f Makefile
	@rm -f *.pyc
	@(cd src && $(MAKE) distclean)



clean: 
	@rm -rf .depends
	@rm -rf *~
	@rm -rf *.o
	@(cd src && touch .depends && $(MAKE) clean)


install: 
	@(cd src && $(MAKE) install)


uninstall: 
	@(cd src && $(MAKE) uninstall)

