# DAVD EBNF

string             := singleQuotedString | doubleQuotedString
singleQuotedString := \" [^"] \"
doubleQuotedString := \' [^'] \'

server := '[[' string ']]'
path   := '[' string ']'

rule     := ( atom '->' rule ) | atom ';' | '{' ruleList '}'
ruleList := rule ruleList
atom     := moduleName
            ( '(', constructionParameters, ')' ) | ''
            ( '[', runtimeParameters, ']' ) | ''

moduleName := [a-z][a-z0-9]*

constructionParameters := parameters | namedParameters
runtimeParameters      := parameters | namedParameters
parameters             := string (',' parameters ) | namedParameters
namedParameters        := ( parameterName '=' string ',' namedParameters ) | ''
parameterName          := [a-z][a-z0-9]*


ROOT := ruleList
